package com.smedialink.tokenplussteamid.app

object AppScreens {
    const val MAIN_SCREEN = "MAIN_SCREEN"
    const val STEAM_AUTH_SCREEN = "AUTH_SCREEN"

    const val FEED_TAB_SCREEN = "FEED_TAB_SCREEN"
    const val PROFILE_TAB_SCREEN = "PROFILE_TAB_SCREEN"
    const val MATCHES_TAB_SCREEN = "MATCHES_TAB_SCREEN"

    const val FEED_SCREEN = "FEED_SCREEN"

    const val MY_PROFILE_SCREEN = "MY_PROFILE_SCREEN"
    const val REPLY_TO_COMMENT_SCREEN = "REPLY_TO_COMMENT_SCREEN"
    const val NO_USER_INFO_SCREEN = "NO_USER_INFO_SCREEN"

    const val USER_DETAILS_SCREEN = "USER_DETAILS_SCREEN"
    const val USER_PROFILE_SCREEN = "USER_PROFILE_SCREEN"
    const val USER_UNREGISTERED_SCREEN = "USER_UNREGISTERED_SCREEN"
    const val ANONYMOUS_WALKTHROUGHT_SCREEN = "ANONYMOUS_WALKTHROUGHT_SCREEN"

    const val MATCH_DETAILS_SCREEN = "MATCH_DETAILS_SCREEN"
    const val RECENT_MATCHES_SCREEN = "RECENT_MATCHES_SCREEN"
}
